services:
  - type: web
    name: civitas
    runtime: node
    plan: free
    autoDeploy: true
    rootDir: .
    buildCommand: npm install --prefix frontend && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: BLOCKFROST_API_KEY
        sync: false
